baseURL = "https://rominap22.github.io/romina-yaps/"
title = "YAPS"
theme = "hextra"
defaultContentLanguage = "en"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

[params.blog.list]
  displayTags = true

[[menu.main]]
  name = "Technical Blog"
  pageRef = "/blog"
  weight = 1

[[menu.main]]
  name = "Musings"
  identifier = "musings"
  weight = 2

[[menu.main]]
  name = "Book Reviews"
  parent = "musings"
  pageRef = "/book-reviews"
  weight = 1

[[menu.main]]
  name = "Health & Fitness"
  parent = "musings"
  pageRef = "/health-fitness"
  weight = 2

[[menu.main]]
  name = "Business"
  parent = "musings"
  pageRef = "/business"
  weight = 3

[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 4

